---
title: "TUBAFsoilFunctions"
output: github_document
editor_options: 
  markdown: 
    wrap: sentence
bibliography: references.bib
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General description
This package contains an assortment of functions used in the soil working group at IBF, TU Bergakademie Freiberg.

### Installation

Install using `remotes::install_github("seanadamhdh/TUBAFsoilFunctions")`.

Currently, packages are loaded lazy with @import`...` instead of @importFrom`...`.
If you are running on a deprecated version of R, try skipping.
It is planned to implement proper import handling at some point, though, for now, you should be fine with R\>4.3 and package versions from 2023 or newer.
If you use legacy versions of the r-packages used by this package, or R itself, you should be careful, as a) Updates could break code written in older versions of R or use legacy versions of package, and b) it might take quite a wile to update everything.
You might want to consider setting up a renv environment.

### Contents

This package contains an assortment of functions that I wrote during my doctorate.
Roughly, they can be grouped into the following categories:

-   Loading, processing, and cleaning of Elementar soliTOCcube data

-   Loading, processing, and cleaning of Bruker Alpha DRIFTS data (heavily relying on @baumann2020, @stevens2022, and @ramirez-lopez2023)

-   Loading, processing and cleaning of Spectrolyzer UV-Vis spectra

-   Chemometric modelling with the caret @kuhn2008 framework, including calibration, validation and application of models for midDRIFTS and UV-Vis data

-   Loading, processing and cleaning (CO2) respiration data collected with SEMACHv3 chamber systems (also see `seanadamhdh/SEMACHv3` for a python single-file exe) and PriEco Pri8800 incubator data

-   Assorted additional functions and helpers for smaller tasks, i.e., for soil profile data homogenisation, or sample label generator.
